const cors = require("cors");
const express = require("express");
const morgan = require("morgan");
const app = express();
const need = require("./routes/needs");
const user = require("./routes/user");
app.use(cors());
app.use(morgan("dev"));
app.use(express.json());
app.use("/api/auth", user);
app.use("/api/needs", need);
module.exports = app;
